import type { Access, CollectionConfig, CollectionBeforeChangeHook, Where } from "payload";
import { hasRole, isAdmin, isEditor, PUBLISH_ROLES } from "../access/roles";
import { enforcePublishOnField, emitContentEvent, onDelete, setCreatedBy } from "../hooks/events";

// Component library read: any signed-in editor (and admins) see everything,
// including drafts. Everyone else — including the unauthenticated AI agent that
// pulls the library at page-build time — sees only LIVE components. Components
// are structural building blocks, not sensitive data.
const componentRead: Access = ({ req: { user } }) => {
  if (hasRole(user, ["author", "reviewer", "publisher", "brand", "siteAdmin", "compliance", "admin"])) return true;
  return { status: { equals: "live" } } as Where;
};

// Editors' components (including ones the Website Builder DELEGATED to the
// Component Agent) start as drafts pending approval — only a publish authority
// may put a component LIVE. This is the component half of Flow B (D3).
const setComponentDefaults: CollectionBeforeChangeHook = ({ data, req, operation }) => {
  if (operation === "create") {
    const roles: string[] = (req.user as any)?.roles ?? [];
    const canPublish = roles.some((r) => (PUBLISH_ROLES as string[]).includes(r));
    if (!canPublish && data.status === "live") data.status = "draft";
  }
  return data;
};

// The CMS component repository. Per the HUMAIN technical review (Jul 2026), the
// CMS is a repository of reusable building-block components (container / section
// / hero / text / image / …); page creation (users + the AI agent) PULLS from
// this library. Admins curate directly; EDITORS (and the delegated Component
// Agent) may create/edit components as DRAFTS, which then require approval before
// they can go LIVE — so a component an Editor triggers never publishes on its own.
export const Components: CollectionConfig = {
  slug: "components",
  admin: {
    useAsTitle: "name",
    defaultColumns: ["name", "type", "category", "status", "aiGenerated", "updatedAt"],
    group: "CMS",
    description: "Reusable building blocks. Admins curate them; the AI agent assembles pages from — and delegates new ones into — the LIVE ones (via approval).",
  },
  access: {
    read: componentRead,
    // Editors may create/edit components (as drafts); the status→live gate below
    // enforces that only publish authorities can put one live (after approval).
    create: isEditor,
    update: isEditor,
    delete: isAdmin,
  },
  hooks: {
    beforeChange: [setCreatedBy, setComponentDefaults, enforcePublishOnField("status", "live")],
    afterChange: [emitContentEvent],
    afterDelete: [onDelete],
  },
  fields: [
    // Create / refine this component with AI, or edit the fields manually below.
    { name: "componentAssist", type: "ui", admin: { components: { Field: "/components/AiComponentAssist#default" } } },
    { name: "name", type: "text", required: true, admin: { description: "Human name shown in the component library." } },
    {
      name: "key",
      type: "text",
      unique: true,
      index: true,
      admin: { description: "Stable reference id the agent uses to pull this block, e.g. hero-split." },
    },
    {
      name: "type",
      type: "select",
      required: true,
      defaultValue: "section",
      options: [
        "container", "section", "hero", "text", "image", "gallery", "card",
        "feature", "cta", "testimonial", "stats", "logoCloud", "pricing",
        "faq", "nav", "footer", "form", "banner",
      ],
      admin: { description: "The kind of building block." },
    },
    {
      name: "category",
      type: "select",
      defaultValue: "content",
      options: ["layout", "content", "media", "navigation", "marketing", "form"],
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "draft",
      options: ["draft", "live"],
      admin: { description: "Only LIVE components are offered to page creation and the AI agent. Going LIVE requires approval (Flow B)." },
    },
    {
      name: "description",
      type: "textarea",
      admin: { description: "What this block is for — guides the agent on when to use it." },
    },
    {
      name: "html",
      type: "code",
      admin: {
        language: "html",
        description: "The block markup. Use {{slot}} / {{prop}} placeholders the agent fills at build time.",
      },
    },
    {
      name: "props",
      type: "json",
      admin: { description: "Schema of the configurable slots/props (name, label, type, default) the agent populates." },
    },
    { name: "tags", type: "array", fields: [{ name: "value", type: "text" }] },
    { name: "previewImage", type: "upload", relationTo: "media" },
    // ---- Governance / approval (Flow B) ----
    {
      name: "aiGenerated",
      type: "checkbox",
      defaultValue: false,
      admin: { position: "sidebar", description: "Generated by the Component Agent (forces at least an editorial review before going live)." },
    },
    {
      name: "riskTier",
      type: "text",
      defaultValue: "low",
      admin: { position: "sidebar", description: "Approval depth: trivial | low | medium | high." },
    },
    {
      name: "delegatedFrom",
      type: "text",
      admin: { position: "sidebar", readOnly: true, description: "The page/build that delegated this component into existence." },
    },
    { name: "createdBy", type: "relationship", relationTo: "users", admin: { position: "sidebar", readOnly: true } },
  ],
  timestamps: true,
};
